/**** CIBLE : MySQL ****/

/*On supprime les tables si elles existent */
DROP TABLE IF EXISTS MARCHANDISE;
DROP TABLE IF EXISTS FLOTTE;
DROP TABLE IF EXISTS CLIENTS;
DROP TABLE IF EXISTS EMPLOYES;
DROP TABLE IF EXISTS UTILISATEURS;

/*Création de la table UTILISATEURS*/
CREATE TABLE UTILISATEURS (
	ID INT NOT NULL AUTO_INCREMENT,
	LOGIN VARCHAR(25) NOT NULL,
	MDP VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID)
);

/*Insertion de l'utilisateur admin*/
INSERT INTO UTILISATEURS(LOGIN,MDP) VALUES('admin','admin');


CREATE TABLE MARCHANDISE(
	ID INT NOT NULL AUTO_INCREMENT,
	
	BATEAU VARCHAR(25),
	DEPART VARCHAR(25),
	DESTINATION VARCHAR(25),
	CLIENT VARCHAR(25),
	POIDS VARCHAR(25),
	
    PRIMARY KEY (ID)
);

/*Insertion de 4 membres*/
INSERT INTO MARCHANDISE(BATEAU,DEPART,DESTINATION,CLIENT,POIDS) VALUES
('Atlantic Champagne','Londres','Rotterdam','Client 1','25 t');
INSERT INTO MARCHANDISE(BATEAU,DEPART,DESTINATION,CLIENT,POIDS) VALUES
('Atlantic Champagne','Londres','Tokyo','Client 2','25 t');
INSERT INTO MARCHANDISE(BATEAU,DEPART,DESTINATION,CLIENT,POIDS) VALUES
('Atlantic Champagne','Londres','Singapour','Client 4','25 t');
INSERT INTO MARCHANDISE(BATEAU,DEPART,DESTINATION,CLIENT,POIDS) VALUES
('Atlantic Champagne','Londres','Le Havre','Client 5','25 t');

/**** CIBLE : MySQL ****/

CREATE TABLE FLOTTE(
	ID INT NOT NULL AUTO_INCREMENT,
	NOM VARCHAR(25),
	LONGUEUR VARCHAR(25),
        LARGEUR VARCHAR(25),
	PORTATTACHE VARCHAR(25),
	CAPACITE VARCHAR(25),
	VITESSE VARCHAR(25),
	LATITUDE VARCHAR(25),
        LONGITUDE VARCHAR(25),
	NBR_CONTAINER VARCHAR(25),
	
    PRIMARY KEY (ID)
);

/*Insertion de 4 membres*/
INSERT INTO FLOTTE(NOM,LONGUEUR,LARGEUR,PORTATTACHE,CAPACITE,VITESSE,LATITUDE,LONGITUDE,NBR_CONTAINER) VALUES
('Atlantic Champagne','212 m','45 m','Rotterdam','70 000 t','25 noeuds','51.9225','4.47917','0');
INSERT INTO FLOTTE(NOM,LONGUEUR,LARGEUR,PORTATTACHE,CAPACITE,VITESSE,LATITUDE,LONGITUDE,NBR_CONTAINER) VALUES
('Colombo Express','212 m','45 m','Rotterdam','70 000 t','25 noeuds','51.9225','4.47917','0');
INSERT INTO FLOTTE(NOM,LONGUEUR,LARGEUR,PORTATTACHE,CAPACITE,VITESSE,LATITUDE,LONGITUDE,NBR_CONTAINER) VALUES
('Emma Maersk','212 m','45 m','Rotterdam','70 000 t','25 noeuds','51.9225','4.47917','0');
INSERT INTO FLOTTE(NOM,LONGUEUR,LARGEUR,PORTATTACHE,CAPACITE,VITESSE,LATITUDE,LONGITUDE,NBR_CONTAINER) VALUES
('CGA CGM Otello','212 m','45 m','Rotterdam','70 000 t','25 noeuds','51.9225','4.47917','0');
INSERT INTO FLOTTE(NOM,LONGUEUR,LARGEUR,PORTATTACHE,CAPACITE,VITESSE,LATITUDE,LONGITUDE,NBR_CONTAINER) VALUES
('OOCL Indonesia','212 m','45 m','Rotterdam','70 000 t','25 noeuds','51.9225','4.47917','0');


CREATE TABLE CLIENTS(
	ID INT NOT NULL AUTO_INCREMENT,
	NOM VARCHAR(25),
	PRENOM VARCHAR(25),
	EMAIL VARCHAR(35),
	TELEPHONE VARCHAR(25),
	SOCIETE VARCHAR(25),
        
    PRIMARY KEY (ID)
);

/*Insertion de 4 membres*/
INSERT INTO CLIENTS (NOM,PRENOM,EMAIL,TELEPHONE,SOCIETE) VALUES
('John','Rambo','john.rambo@gmail.com','0636959874','Client1');
INSERT INTO CLIENTS (NOM,PRENOM,EMAIL,TELEPHONE,SOCIETE) VALUES
('Bill','Termendous','bill.tremendous@gmail.com','0648965123','client2');
INSERT INTO CLIENTS (NOM,PRENOM,EMAIL,TELEPHONE,SOCIETE) VALUES
('Frodon','Baggins','frodon.baggins@gmail.com','0765983265','client3');


CREATE TABLE EMPLOYES(
	ID INT NOT NULL AUTO_INCREMENT,
	NOM VARCHAR(25),
	PRENOM VARCHAR(25),
    TELDOM VARCHAR(10),
	TELPORT VARCHAR(10),
	TELPRO VARCHAR(10),
	ADRESSE VARCHAR(150),
	CODEPOSTAL VARCHAR(15),
	VILLE VARCHAR(25),
	EMAIL VARCHAR(25),
    PRIMARY KEY (ID)
);

/*Insertion de 4 membres*/
INSERT INTO EMPLOYES(NOM,PRENOM,TELDOM,TELPORT,TELPRO,ADRESSE,CODEPOSTAL,VILLE,EMAIL) VALUES
('Bond','James','0123456789','0612345678','0698765432','2 avenue 007','92700','Colombes','jbond@gmail.com');
INSERT INTO EMPLOYES(NOM,PRENOM,TELDOM,TELPORT,TELPRO,ADRESSE,CODEPOSTAL,VILLE,EMAIL) VALUES
('Jones','Indiana','0145362787','0645362718','0611563477','10 rue des Aventuriers','92270','Bois-colombes','ijones@gmail.com');
INSERT INTO EMPLOYES(NOM,PRENOM,TELDOM,TELPORT,TELPRO,ADRESSE,CODEPOSTAL,VILLE,EMAIL) VALUES
('Bourne','Jason','0187665987','0623334256','0654778654','65 rue Agent Secret Perdu','92700','Colombes','jbourne@yahoo.fr');
INSERT INTO EMPLOYES(NOM,PRENOM,TELDOM,TELPORT,TELPRO,ADRESSE,CODEPOSTAL,VILLE,EMAIL) VALUES
('Stark','Arya','0187611987','0783334256','0658878654','6 rue Sans-Nom','75016','Paris','astark@nord.com');
INSERT INTO EMPLOYES(NOM,PRENOM,TELDOM,TELPORT,TELPRO,ADRESSE,CODEPOSTAL,VILLE,EMAIL) VALUES
('Lanister','Cersei','0187384987','0622494256','0674178654','5 bvd des Reines','21000','Dijon','clanister@mail.co.uk');
